- hosts: all
  sudo: yes

  tasks:
    - name: Copy members key to Authorized_keys
      copy: 
        src: authorized_keys
        dest: .ssh/authorized_keys
    - name: prepare install CouchDB
      lineinfile:
        dest: /etc/apt/sources.list
        line: deb http://apache.bintray.com/couchdb-deb xenial main
        insertafter: EOF
    - name: install CouchDB
      environment: 
          DEBIAN_FRONTEND: noninteractive
      apt:
        name: couchdb
        force: yes
        allow_unauthenticated: yes

    